### ISSUE TITLE
avoiding alignment question

### ISSUE THREAD

**Issue by astearns** [dbaron/css-line-spacing#1]
I am unclear about the motivation behind this statement:

> it should also be possible to avoid alignment of baselines in adjacent boxes

Is it just the requirement that you need to be able to opt-out of grid/step alignment, or is there a particular use case for non-alignment of side-by-side content you're thinking of?

**Comment by dbaron** [comment]
The intent was that I was just saying that you should be able to opt out.  I should probably reword the paragraph, though...
